spring:
  application:
    name: AkjonavBaseApp

server:
  servlet:
    context-path: /akjonav/base
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /api-docs

firebase:
  credential:
    path: Akjonav-Base/src/main/resources/private/akjonav-0e21ee11c4ba.json