spring:
  application:
    name: AkjonavBaseApp

server:
  servlet:
    context-path: /akjonav/base
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /api-docs