spring:
  application:
    name: AkjonavBaseApp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/

server:
  servlet:
    context-path: /akjonav/base
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /api-docs
  use-fqn: true
  swagger-ui:
    default-model-expand-depth: -1

auth0:
  client-id: ${env.AUTH_CLIENT_ID}
  client-secret: ${env.AUTH_CLIENT_SECRET}

  domain: akjo03.eu.auth0.com
  audience: api.akjonav.io

.env:
  directory: ./.env
  ignoreIfMissing: false